# Generated by Django 5.2.1 on 2025-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='provincia',
            field=models.CharField(blank=True, choices=[('Álava', 'Álava'), ('Albacete', 'Albacete'), ('Alicante', 'Alicante'), ('Almería', 'Almería'), ('Asturias', 'Asturias'), ('Ávila', 'Ávila'), ('Badajoz', 'Badajoz'), ('Barcelona', 'Barcelona'), ('Burgos', 'Burgos'), ('Cáceres', 'Cáceres'), ('Cádiz', 'Cádiz'), ('Castellón', 'Castellón'), ('Ciudad Real', 'Ciudad Real'), ('Córdoba', 'Córdoba'), ('Cuenca', 'Cuenca'), ('Gerona', 'Gerona'), ('Granada', 'Granada'), ('Guadalajara', 'Guadalajara'), ('Guipúzcoa', 'Guipúzcoa'), ('Huelva', 'Huelva'), ('Huesca', 'Huesca'), ('Jaén', 'Jaén'), ('La Rioja', 'La Rioja'), ('Las Palmas', 'Las Palmas'), ('León', 'León'), ('Lérida', 'Lérida'), ('Lugo', 'Lugo'), ('Madrid', 'Madrid'), ('Málaga', 'Málaga'), ('Murcia', 'Murcia'), ('Navarra', 'Navarra'), ('Orense', 'Orense'), ('Palencia', 'Palencia'), ('Pontevedra', 'Pontevedra'), ('Salamanca', 'Salamanca'), ('Segovia', 'Segovia'), ('Sevilla', 'Sevilla'), ('Soria', 'Soria'), ('Tarragona', 'Tarragona'), ('Teruel', 'Teruel'), ('Toledo', 'Toledo'), ('Valencia', 'Valencia'), ('Valladolid', 'Valladolid'), ('Vizcaya', 'Vizcaya'), ('Zamora', 'Zamora'), ('Zaragoza', 'Zaragoza')], max_length=50, null=True),
        ),
    ]
