# Generated by Django 5.2.1 on 2025-05-26 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10)),
                ('genero', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('edad', models.IntegerField()),
                ('tamano', models.CharField(choices=[('pequeño', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=10)),
                ('raza', models.CharField(max_length=100)),
                ('temperamento', models.TextField()),
                ('historia', models.TextField()),
                ('apto_ninos', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('precaucion', 'Precaución'), ('noRecomendado', 'No recomendado'), ('desconocido', 'Desconocido')], max_length=20)),
                ('compatibilidad_mascotas', models.CharField(choices=[('excelente', 'Excelente'), ('bienConPerros', 'Bien con perros'), ('bienConGatos', 'Bien con gatos'), ('selectivo', 'Selectivo'), ('prefiereSolo', 'Prefiere estar solo'), ('desconocido', 'Desconocido')], max_length=20)),
                ('apto_piso_pequeno', models.CharField(choices=[('ideal', 'Ideal'), ('bueno', 'Bueno'), ('requiereEspacio', 'Requiere espacio'), ('soloConJardin', 'Solo con jardín'), ('desconocido', 'Desconocido')], max_length=20)),
                ('esterilizado', models.BooleanField()),
                ('problema_salud', models.BooleanField(default=False)),
                ('descripcion_salud', models.CharField(blank=True, max_length=255)),
                ('imagen1', models.URLField(blank=True)),
                ('imagen2', models.URLField(blank=True)),
                ('imagen3', models.URLField(blank=True)),
                ('imagen4', models.URLField(blank=True)),
                ('empresa', models.ForeignKey(limit_choices_to={'tipo': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
