# Generated by Django 5.2.1 on 2025-05-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='edad',
        ),
        migrations.AddField(
            model_name='animal',
            name='fecha_nacimiento',
            field=models.DateField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
