# Generated by Django 5.2.1 on 2025-05-26 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_remove_animal_edad_animal_fecha_nacimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='empresa',
            field=models.ForeignKey(limit_choices_to={'tipo': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='animales', to=settings.AUTH_USER_MODEL),
        ),
    ]
