# Generated by Django 5.2.1 on 2025-06-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_alter_animal_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagen1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen4',
            field=models.URLField(blank=True, null=True),
        ),
    ]
