# Generated by Django 5.2.1 on 2025-06-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_alter_animal_imagen1_alter_animal_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('No adoptado', 'No adoptado'), ('En proceso', 'En proceso'), ('Adoptado', 'Adoptado')], default='No adoptado', max_length=30),
        ),
    ]
