# Generated by Django 5.2.1 on 2025-06-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biografia',
            field=models.TextField(blank=True),
        ),
    ]
